### ISSUE TITLE
Stop polling queue in case response is recieved

### ISSUE THREAD

**Issue by annapuskarjova** [ctco/cukes-rest#27]
STEP:
And should wait at most 30 seconds with interval 1 seconds until property "status" equal to "SUCCEEDED"

Problem description:
When, for whatever reason, a write operation fails, the test don't stop polling the queue, but the status already received and it is "FAILED".
We would like to have that the test stop polling a queue in case response is received.

**Comment by AlexeyBuzdin** [comment]
Add failureMatcher to AwaitCondition

**Comment by AlexeyBuzdin** [comment]
Closed
