### ISSUE TITLE
Please add variable support for LR plugin

### ISSUE THREAD

**Issue by annapuskarjova** [ctco/cukes-rest#30]
Load runner script generator is not able to set variable to LoadRunner script

in cukes:
  And let variable "modelSectionId" equal to "4"
  When the client performs GET request on api/modelsections/{**(modelSectionId)**}

genered script:
web_custom_request("GET to http://localhost:8080/cih/api/modelsections/**(modelSectionId)**",
"URL=http://localhost:8080/cih/api/modelsections/(modelSectionId)",

**Comment by sergeytrasko** [comment]
Mainly there are 3 use cases for it:
1. Variable is taken from response body
2. Variable is taken from response header
3. Variable is set explicitly

These 3 use cases require different handling during LR script generation

**Comment by sergeytrasko** [comment]
Already implemented, please close
