### ISSUE TITLE
LR body in the request should be one row

### ISSUE THREAD

**Issue by annapuskarjova** [ctco/cukes-rest#40]
Currently in some cases the request body in not generated in one row and LoadRunner throws script compilation error.

web_custom_request("POST to http://localhost:8080/cih/api/contracts/%28contractId%29/involvedparties/",
 "URL=http://localhost:8080/cih/api/contracts/%28contractId%29/involvedparties/",
 "Method=POST",
 "Resource=0",
 "Mode=http",
 "Body={
  \"partnerId\":2203934,
  \"partnerRole\":2165
}",
 "Snapshot=t7198821076.inf",
 LAST);

**Comment by AlexeyBuzdin** [comment]
You would like to have the whole Body put in a single line? Will it be not hard to read?

**Comment by annapuskarjova** [comment]
It's hard to read, but LoadRunner do not understand if it's not one line.

**Comment by sergeytrasko** [comment]
Already implemented, please close
