### ISSUE TITLE
Is cukes-rest double encoding query parameters?

### ISSUE THREAD

**Issue by yegeniy** [ctco/cukes-rest#43]
I was just talking with @clee681 and it seems that https://github.com/ctco/cukes-rest/blob/4961e4adc9fd5c7c5e8e4e02b7d2dbf477ec1b84/cukes-rest/src/main/java/lv/ctco/cukesrest/internal/RequestSpecificationFacade.java#L71-L78 might be double encoding a query parameter such as `foo=bar(baz)`

**Comment by yegeniy** [comment]
Looks like using a snapshot build that includes https://github.com/ctco/cukes-rest/commit/689f26535bd282d1638837efcccbc0e5c876dd36 fixed the issue. 

Is it possible to publish a patch release `0.2.13` to maven central?

**Comment by AlexeyBuzdin** [comment]
Hi @yegeniy and @clee681 started deployment to Maven Central with the fixed version https://snap-ci.com/ctco/cukes-rest/branch/master/logs/defaultPipeline/74/Publish_version?back_to=build_history . Should be there in ~2-6 hours. 

If you have any other problems or questions with cukes-rest, please don't hesitate to write. Would be glad to assist :)

**Comment by creeefs** [comment]
Thanks @AlexeyBuzdin!

**Comment by yegeniy** [comment]
> If you have any other problems or questions with cukes-rest, please don't hesitate to write.

So far, cukes-rest has been solving my problems :) 
Thanks for the quick turnaround.
