### ISSUE TITLE
Publish 0.2.0 version to mvn central

### ISSUE THREAD

**Issue by AlexeyBuzdin** [ctco/cukes-rest#5]

**Comment by Quesar** [comment]
Version 0.2.0 has passed requirement checks and has been pushed to Sonatype releases repository -- https://oss.sonatype.org/content/repositories/releases/lv/ctco/cukesrest/ via Snap-CI pipeline.
Sonatype has been notified about the first release and should enable actual synchronization to Maven Central.

**Comment by Quesar** [comment]
Version 0.2.0 is available on Maven Central -- http://search.maven.org/#artifactdetails|lv.ctco.cukesrest|cukes-rest-all|0.2.0|pom
