### ISSUE TITLE
Show error messege in test

### ISSUE THREAD

**Issue by annapuskarjova** [ctco/cukes-rest#52]
In case than on server side occurs an error we would like to have a possibility to print the error message in test. Right now we just see that status code is not like expected.

When we wait for 200 response with certain value and if that value is matched "FAILURE", then print element from that response (e.g. here "errors")

**Comment by IgorGursky** [comment]
+1

**Comment by jromero** [comment]
By error message do we mean response body?

**Comment by AlexeyBuzdin** [comment]
@jromero yeap :)

**Comment by jromero** [comment]
Cool, I was thinking so because we were needing it as well. I might try to get a PR up for this.

**Comment by jromero** [comment]
I tried looking into this recently and found that there is a [bug](https://github.com/rest-assured/rest-assured/issues/781) with RestAssured which prevents resolving this by use of a Matcher.

It feels dirty but works.. what do you guys think about something like this?

```java
final String body = facade.response().getBody().print();

try {
    facade.response().then().statusCode(statusCode);
} catch (AssertionError error) {
    throw new AssertionError(error.getMessage() + "Body:\n" + body);
}
```

A few things I think should be included:

1. Globally enabled/disabled via config.
2. Configurable max size for body to be printed.
    * We wouldn't want to print out a huge response.
3. Automatically ignore content-type `application/octet-stream` (aka binary data).
