### ISSUE TITLE
Need API for AssertionFacadeImpl.bodyContainsArrayGreaterThanSize(String path, String size)

### ISSUE THREAD

**Issue by sandeep540** [ctco/cukes-rest#70]
Need API for AssertionFacadeImpl.bodyContainsArrayGreaterThanSize(String path, String size) for checking if the result size is more than given size

similar for < would be great

**Comment by sergeytrasko** [comment]
That is already supported, something like this:
```
When the client performs GET request to /persons
Then status code is 200
And response contains an array "results" of size > 10
```
Please refer to [ThenSteps.java](https://github.com/ctco/cukes-rest/blob/master/cukes-rest/src/main/java/lv/ctco/cukesrest/api/ThenSteps.java#L89)

Does it cover your use case?

**Comment by sandeep540** [comment]
Yes @sergeytrasko , it covers, my bad, did not check the complete API. Thanks a lot for quick info
