### ISSUE TITLE
Java 8 Support

### ISSUE THREAD

**Issue by trioletas** [ctco/cukes-rest#83]
We believe it makes sense to migrate the code base to JDK8. It's a pretty stable SDK that has been out for 4 years now and some of the features introduced in this version of the language would help us to improve the source code quite a bit (lambdas, streams and optional types are handy).

Are there any concerns from the community w.r.t this (breaking) change?
I realize that there's several platforms that do not support JDK8 yet (e.g. Google's PaaS cloud is still running 8 in beta and many enterprises are in the same situation).

**Comment by IgorGursky** [comment]
Along with modularization initiative in Cukes, we have already trying to do an upgrade.
First version is about to be released.

**Comment by IgorGursky** [comment]
Released in 0.0.1!
